### ISSUE TITLE
Latest aurelia fix (beta JSPM support) seems to break aurelia-flux

### ISSUE THREAD

**Issue by whtdrgn101** [Aesthetickz/aurelia-flux#2]
System JS blows up when trying to load the aurelia-flux config after the JSPM update from the last Aurelia release:

EBUG [aurelia] Loading plugin aurelia-flux.
shim.min.js:1444 Unhandled promise rejection Error: Pipeline steps can only be added to the root router
    at RouterConfiguration.exportToRouter (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:896:17)
    at Router.configure (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:963:26)
    at Function.AddFluxPipelineStep (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/router.js:19:14)
    at a.configure (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/index.js:14:31)
    at http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/framework@0.14.0/aurelia-framework.js:25:34
    at f (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)(anonymous function) @ shim.min.js:1444
shim.min.js:1444 Unhandled promise rejection Error: Pipeline steps can only be added to the root router
    at RouterConfiguration.exportToRouter (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:896:17)
    at Router.configure (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:963:26)
    at Function.AddFluxPipelineStep (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/router.js:19:14)
    at a.configure (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/index.js:14:31)
    at http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/github/aurelia/framework@0.14.0/aurelia-framework.js:25:34
    at f (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (http://ec2-54-148-60-1.us-west-2.compute.amazonaws.com:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)

**Comment by stevies** [comment]
Getting similar:
```
DEBUG [aurelia] Loading plugin aurelia-flux.
es6.promise.js:139 Unhandled promise rejection Error: Pipeline steps can only be added to the root router
    at RouterConfiguration.exportToRouter (http://localhost:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:896:17)
    at Router.configure (http://localhost:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:963:26)
    at Function.AddFluxPipelineStep (http://localhost:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/router.js:19:14)
    at a.configure (http://localhost:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/index.js:14:31)
    at http://localhost:9000/jspm_packages/github/aurelia/framework@0.14.0/aurelia-framework.js:25:34
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Error: Pipeline steps can only be added to the root router
    at RouterConfiguration.exportToRouter (http://localhost:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:896:17)
    at Router.configure (http://localhost:9000/jspm_packages/github/aurelia/router@0.10.4/aurelia-router.js:963:26)
    at Function.AddFluxPipelineStep (http://localhost:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/router.js:19:14)
    at a.configure (http://localhost:9000/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.6/index.js:14:31)
    at http://localhost:9000/jspm_packages/github/aurelia/framework@0.14.0/aurelia-framework.js:25:34
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)
```

**Comment by Aesthetickz** [comment]
Did this work before? Because this was never intended to work as a plugin, it was just a try out project.

**Comment by whtdrgn101** [comment]
Yes, it worked just fine before the latest round of aurelia updates.

**Comment by stevies** [comment]
Same for me.  Was not using it for anything serious, but had it working nicely in a simple test application.

**Comment by Aesthetickz** [comment]
oh it's a plugin with the same name :package: hehe.
